# Generated by Django 4.2.4 on 2026-04-12 14:13

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("otomoto_ad_id", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "public_slug",
                    models.CharField(blank=True, help_text="Short ID from URL, e.g. ID6HSO0m", max_length=32),
                ),
                ("url", models.URLField(max_length=1024)),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                ("price_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("price_currency", models.CharField(default="PLN", max_length=8)),
                ("price_labels", models.JSONField(blank=True, default=list)),
                ("price_drop", models.JSONField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("mileage_km", models.PositiveIntegerField(blank=True, null=True)),
                ("engine_cc", models.PositiveIntegerField(blank=True, null=True)),
                ("engine_power_hp", models.PositiveIntegerField(blank=True, null=True)),
                ("fuel_type", models.CharField(blank=True, max_length=64)),
                ("gearbox", models.CharField(blank=True, max_length=64)),
                ("transmission", models.CharField(blank=True, max_length=128)),
                ("body_type", models.CharField(blank=True, max_length=64)),
                ("color", models.CharField(blank=True, max_length=64)),
                ("doors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("make", models.CharField(blank=True, max_length=128)),
                ("make_slug", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("model_slug", models.CharField(blank=True, max_length=128)),
                ("vin", models.CharField(blank=True, max_length=32)),
                ("country_origin", models.CharField(blank=True, max_length=128)),
                ("date_registration", models.CharField(blank=True, max_length=128)),
                ("damaged", models.BooleanField(blank=True, null=True)),
                ("no_accident", models.BooleanField(blank=True, null=True)),
                ("registered", models.BooleanField(blank=True, null=True)),
                ("service_record", models.BooleanField(blank=True, null=True)),
                ("vat", models.CharField(blank=True, max_length=64)),
                ("new_used", models.CharField(blank=True, max_length=32)),
                ("seller_type", models.CharField(blank=True, max_length=32)),
                ("seller_name", models.CharField(blank=True, max_length=256)),
                ("seller_otomoto_id", models.CharField(blank=True, max_length=32)),
                ("seller_uuid", models.CharField(blank=True, max_length=64)),
                ("seller_url", models.URLField(blank=True, max_length=1024)),
                ("seller_website", models.URLField(blank=True, max_length=1024)),
                ("seller_location", models.JSONField(blank=True, null=True)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("main_features", models.JSONField(blank=True, default=list)),
                ("otomoto_created_at", models.DateTimeField(blank=True, null=True)),
                ("otomoto_updated_at", models.DateTimeField(blank=True, null=True)),
                ("raw_advert", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-otomoto_created_at", "-created"),
            },
        ),
    ]
