# Generated by Django 4.2.4 on 2026-04-12 14:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_car_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoScout24Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "listing_guid",
                    models.CharField(
                        db_index=True,
                        help_text="Listing UUID from AutoScout24 (id field in API payload).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(max_length=1024)),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                ("price_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("price_currency", models.CharField(default="EUR", max_length=8)),
                ("price_display", models.CharField(blank=True, max_length=64)),
                ("price_tax_deductible", models.BooleanField(blank=True, null=True)),
                ("mileage_km", models.PositiveIntegerField(blank=True, null=True)),
                ("first_registration_raw", models.CharField(blank=True, max_length=32)),
                ("first_registration_date", models.DateField(blank=True, null=True)),
                ("production_year", models.PositiveIntegerField(blank=True, null=True)),
                ("fuel_type", models.CharField(blank=True, max_length=64)),
                ("transmission", models.CharField(blank=True, max_length=64)),
                ("drive_train", models.CharField(blank=True, max_length=64)),
                ("body_type", models.CharField(blank=True, max_length=64)),
                ("color", models.CharField(blank=True, max_length=64)),
                ("paint_type", models.CharField(blank=True, max_length=64)),
                ("doors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("engine_cc", models.PositiveIntegerField(blank=True, null=True)),
                ("engine_power_hp", models.PositiveIntegerField(blank=True, null=True)),
                ("engine_power_kw", models.PositiveIntegerField(blank=True, null=True)),
                ("gears", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("co2_g_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fuel_consumption_l100km_combined",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("make", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("model_version", models.CharField(blank=True, max_length=256)),
                ("variant", models.CharField(blank=True, max_length=128)),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("had_accident", models.BooleanField(blank=True, null=True)),
                ("has_full_service_history", models.BooleanField(blank=True, null=True)),
                ("non_smoking", models.BooleanField(blank=True, null=True)),
                ("previous_owners", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("next_inspection_raw", models.CharField(blank=True, max_length=32)),
                ("seller_type", models.CharField(blank=True, max_length=32)),
                ("seller_company", models.CharField(blank=True, max_length=256)),
                ("seller_contact", models.CharField(blank=True, max_length=256)),
                ("seller_as24_id", models.CharField(blank=True, max_length=32)),
                ("seller_sell_id", models.CharField(blank=True, max_length=32)),
                ("seller_is_dealer", models.BooleanField(blank=True, null=True)),
                ("seller_links", models.JSONField(blank=True, null=True)),
                ("location", models.JSONField(blank=True, null=True)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("listing_created_at", models.DateTimeField(blank=True, null=True)),
                ("raw_listing", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-listing_created_at", "-created"),
            },
        ),
    ]
