# Generated by Django 4.2.4 on 2026-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_unified_car_offer_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="caroffer",
            name="audio_system",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown / not set"),
                    ("bowers_wilkins", "Bowers & Wilkins"),
                    ("harman_kardon", "Harman Kardon"),
                    ("standard", "Standard audio"),
                    ("other_premium", "Other premium"),
                ],
                db_index=True,
                default="",
                help_text="Use model year + this to separate Sensus vs Google-based eras.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_ambient_lighting_package",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_awd",
            field=models.BooleanField(blank=True, help_text="All-wheel drive (e.g. V90 CC AWD vs FWD V90).", null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_city_safety",
            field=models.BooleanField(
                blank=True, help_text="AEB with pedestrian / cyclist / large animal detection.", null=True
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_cross_traffic_alert_reverse_brake",
            field=models.BooleanField(
                blank=True, help_text="Cross Traffic Alert with auto-brake when reversing.", null=True
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_crystal_gear_selector",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_folding_rear_headrests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_four_zone_climate",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_front_rear_parking_sensors",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_google_built_in_infotainment",
            field=models.BooleanField(blank=True, help_text="Google Maps, Assistant, Play Store built-in.", null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_hill_descent_control",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_increased_clearance_off_road_mode",
            field=models.BooleanField(
                blank=True, help_text="Raised ground clearance and Off Road drive mode.", null=True
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_panoramic_roof",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_pilot_assist",
            field=models.BooleanField(
                blank=True, help_text="Adaptive cruise + lane-keeping steering assist.", null=True
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_power_tailgate",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_rear_air_suspension",
            field=models.BooleanField(
                blank=True,
                help_text="Rear-only or four-corner adaptive air suspension with self-levelling at rear.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_remote_rear_seatback_release",
            field=models.BooleanField(blank=True, help_text="Release rear seatbacks from the cargo area.", null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_surround_view_camera_360",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="feature_wood_or_metal_inlays",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caroffer",
            name="public_slug",
            field=models.CharField(blank=True, help_text="Otomoto: short ID from URL, e.g. ID6HSO0m", max_length=32),
        ),
    ]
