# Generated by Django 4.2.4

from django.db import migrations, models


def backfill_pneumatic_from_rear_air(apps, schema_editor):
    CarOffer = apps.get_model("offers", "CarOffer")
    CarOffer.objects.filter(feature_rear_air_suspension=True).update(feature_pneumatic_suspension=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_car_offer_equipment_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="caroffer",
            name="feature_pneumatic_suspension",
            field=models.BooleanField(
                blank=True,
                help_text="Pneumatic or adaptive air suspension (PL: zawieszenie pneumatyczne, Four-C; EN: pneumatic/air suspension, Airmatic).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="headlight_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown / not set"),
                    ("halogen", "Halogen"),
                    ("xenon", "Xenon / Bi-xenon / HID"),
                    ("led", "LED"),
                    ("matrix_led", "Matrix / Pixel / adaptive LED"),
                    ("laser", "Laser headlights"),
                    ("other_premium", "Other adaptive / premium lighting"),
                ],
                db_index=True,
                default="",
                help_text="Main headlight type inferred from listing (PL/EN). Fog-only LED may still classify as LED.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="upholstery_color",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="engine_model",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="wheel_size",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="caroffer",
            name="listing_location",
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="caroffer",
            name="feature_rear_air_suspension",
            field=models.BooleanField(
                blank=True,
                help_text="Legacy combined flag: rear self-levelling and/or full pneumatic air suspension.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_pneumatic_from_rear_air, noop_reverse),
    ]
