# Generated by Django 2.1.7 on 2019-02-21 20:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cars_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dealer',
            name='country',
            field=models.CharField(default='I', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='url_name',
            field=models.CharField(default='I', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerstats',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer'),
        ),
    ]
