# Generated by Django 2.1.7 on 2019-02-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_auto_20190221_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='url',
        ),
        migrations.AddField(
            model_name='dealer',
            name='Street',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='average_ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='company_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='geo_lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='geo_long',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='zip',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
