# Generated by Django 2.1.7 on 2019-02-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20190222_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='Street',
            new_name='street',
        ),
    ]
