# Generated by Django 2.1.7 on 2019-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_auto_20190222_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='country',
            field=models.CharField(choices=[('I', 'Italy'), ('F', 'France'), ('D', 'Germany')], max_length=1),
        ),
    ]
