# Generated by Django 2.1.7 on 2019-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_auto_20190222_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealerstats',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='dealer',
            name='cars_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
