# Generated by Django 2.1.7 on 2019-02-24 20:35

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0007_auto_20190224_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('info', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=64)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
