# Generated by Django 2.1.7 on 2019-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0008_dealercar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealercar',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
