# Generated by Django 4.2.4 on 2023-08-31 08:22

import django.db.models.deletion
import django_extensions.db.fields
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=128)),
                ("zip", models.CharField(max_length=16)),
                ("city", models.CharField(max_length=64)),
                (
                    "country",
                    models.CharField(choices=[("I", "Italy"), ("F", "France"), ("D", "Germany")], max_length=1),
                ),
                ("autoscout_data", models.JSONField()),
                ("cars_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DealerStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("cars_count", models.PositiveIntegerField()),
                ("dealer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dealers.dealer")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="DealerCar",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("info", models.CharField(max_length=64)),
                ("url", models.CharField(max_length=256)),
                ("dealer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dealers.dealer")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
